/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import entities.Booking;
import entities.Trip;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.BookingDAO;
import models.BookingSQLite;
import models.TripDAO;
import models.TripSQLite;

/**
 *
 * @author tegar
 */
public class TicketBookingPanel extends javax.swing.JPanel {

    /**
     * Creates new form TicketBookingPanel
     */
    private BookingDAO bookingDAO;
    private TripDAO tripDAO;
    
    public TicketBookingPanel() {
        initComponents();
        bookingDAO = new BookingSQLite();
        tripDAO = new TripSQLite();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerContact = new javax.swing.JTextField();
        txtTripID = new javax.swing.JTextField();
        txtBuyAmount = new javax.swing.JTextField();
        btnConfirmReceipt = new javax.swing.JButton();

        jLabel1.setText("Nama");

        txtReceipt.setEditable(false);
        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane2.setViewportView(txtReceipt);

        jLabel2.setText("Kontak");

        jLabel4.setText("ID Rute");

        jLabel5.setText("Jumlah");

        btnConfirmReceipt.setText("Pesan");
        btnConfirmReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerContact))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuyAmount)
                            .addComponent(txtTripID)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmReceipt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCustomerContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTripID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtBuyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmReceipt)
                        .addGap(0, 221, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(10, 10, 10)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmReceiptActionPerformed
        try {
            String customerName = txtCustomerName.getText();
            String customerContact = txtCustomerContact.getText();
            String tripID = txtTripID.getText();
            int buyAmount = Integer.parseInt(txtBuyAmount.getText());

            // Get trip by ID
            Trip trip = tripDAO.getTripById(tripID);
            if (trip == null) {
                JOptionPane.showMessageDialog(this, "Trip with ID " + tripID + " not found.");
                return;
            }

            // Check if enough tickets are available
            if (trip.getTicketAmount() < buyAmount) {
                JOptionPane.showMessageDialog(this, "Not enough tickets available.");
                return;
            }

            // Calculate total price
            double totalPrice = trip.getPrice() * buyAmount;

            // Create new booking
            LocalDateTime bookingDate = LocalDateTime.now();
            Booking booking = new Booking(tripID, customerName, customerContact, bookingDate, buyAmount);
            bookingDAO.addBooking(booking);

            // Update trip ticket amount
            trip.setTicketAmount(trip.getTicketAmount() - buyAmount);
            tripDAO.updateTrip(trip);

            // Show confirmation message
            JOptionPane.showMessageDialog(this, "Booking confirmed!");

            // Display booking details in receipt area
            txtReceipt.append("==== NOTA =====\n\n");
            txtReceipt.append("Nama: " + customerName + "\n\n");
            txtReceipt.append("Kontak: " + customerContact + "\n\n");
            txtReceipt.append("ID Rute: " + tripID + "\n\n");
            txtReceipt.append("Jumlah: " + buyAmount + "\n\n");
            txtReceipt.append("Tanggal Pemesanan: " + booking.getBookingDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + "\n\n");
            txtReceipt.append("---------------------------------------\n\n");
            txtReceipt.append("Total Harga: " + totalPrice + "\n\n");

            // Clear all input fields
            txtCustomerName.setText("");
            txtCustomerContact.setText("");
            txtTripID.setText("");
            txtBuyAmount.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for the amount.");
        }
    }//GEN-LAST:event_btnConfirmReceiptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmReceipt;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBuyAmount;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextArea txtReceipt;
    private javax.swing.JTextField txtTripID;
    // End of variables declaration//GEN-END:variables
}
