/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UAS_PBO_FinalProject;

import GUI.MainPage;
import helpers.SetupDB;
import java.awt.List;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SetupDB.migrate();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
}
